#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'bundler/setup'
require 'k8s/templates/compiler'
require 'benchmark'

compiler = K8s::Templates::Compiler::Cli.new
result = 0

time = Benchmark.realtime do
  result = compiler.run
end

puts "Finished in #{time} seconds" if compiler.options[:debug]
exit result
